int add(int a,int b);
float subtract(float a,float b);
float multiply(float a,float b);
float divide(float a,float b);
int fact(int n);
int npr(int n,int r);
int ncr(int n,int r);
 int power(int x,int y);
 void quadratic_roots(double a_1,double b_1,double c_1);
 float exponential(float x);
 float sine_value(float x);
 float cos_value(float x);
 float tan_value(float x);
int determinant();
float square(float x);
float cube(float x);